@@include('./site.inc')
@@include('./top.inc')
<div class="screen-outer">
  <div class="screen-inner wrap clear">
    @@include('./outerNav.inc')
    <div class="service-hd">Yahoo!JAPAN拍卖分类</div>
    <div class="yahoo-service" id="yahooService" style="width: 220px;"></div>
    <div class="yahoo-promo" id="PromoSlide"></div>
    <div class="yahoo-right">
      <div class="ad-box">
        <img src="../Public/images/addbannercjwti.png" alt="" width="100%">
      </div>
      <div class="ts-service-box">
        <div class="tss-title">买下11区&sdot;特色服务</div>
        <div class="tss-list">
          <a href="javascript:void(0);"><i class="iconfont icon-zuanshi"></i>先得标再付款，免预付额</a>
          <a href="javascript:void(0);"><i class="iconfont icon-zuanshi"></i>24小时系统自动出价、充值</a>
          <a href="javascript:void(0);"><i class="iconfont icon-zuanshi"></i>业界最低费用、最高回馈</a>
          <a href="javascript:void(0);"><i class="iconfont icon-zuanshi"></i>自动式竞拍</a>
          <a href="javascript:void(0);"><i class="iconfont icon-zuanshi"></i>全通明的信息与收费</a>
        </div>
      </div>
    </div>
  </div>
</div>
